@startuml

actor User as user 
actor Root as root
participant VPS as serv

root -> serv : update && upgrade
group Add user
    root -> serv : add user
    root -> serv : add sudo group
end 
group Close ssh root
    root -> serv : close root login
    root -> serv : change port
end

root -X serv : can't connect root
root -X serv : can't connect port 22

group first ufw settings
    user -> serv : install ufw
    user -> serv : change port in OpenSSH application ufw
    user -> serv : add rules OpenSSH
    user -> serv : enable ufw
end

group keys 
    user -> user : generate key
    user -> serv : add publick key
    user -> serv : close password login
end

user -X serv : login without key


@enduml